spring:
  application:
    name: service-auth2 
server:
  port: 5002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      filter-order: 3